---

plugins:
  - jest
env:
  es2020: true
  node: true
  jest: true
extends:
  - airbnb-base
  - plugin:jest/recommended
parserOptions:
  ecmaVersion: 2020
  sourceType: module
rules:
  no-console: off
  import/extensions: off
  import/prefer-default-export: off
  jest/no-try-expect: off
  jest/no-conditional-expect: off
